spring:
  profiles:
    active: local

  application:
    name: board-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms  # ?? ???? ??
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug

---
# Local Profile (H2)
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""  # ?? ? ???? ??

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: your-secret-key-for-jwt-token-generation-must-be-at-least-256-bits-long
  access-token-validity: 3600000
  refresh-token-validity: 604800000

---
# Production Profile (MySQL)
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET:default-secret-key-for-jwt-token-generation-must-be-at-least-256-bits-long}
  access-token-validity: ${JWT_ACCESS_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY:604800000}