spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: test-secret-key-for-jwt-token-generation-must-be-at-least-256-bits-long
  access-token-validity: 3600000
  refresh-token-validity: 604800000

logging:
  level:
    org.hibernate.SQL: debug
